386_OBJECTS= \
    $(_OBJ_DIR)\i386\driverentry.obj \
    $(_OBJ_DIR)\i386\stddcls.obj

PASS0_386_OBJECTS=

IA64_OBJECTS= \
    $(_OBJ_DIR)\ia64\driverentry.obj \
    $(_OBJ_DIR)\ia64\stddcls.obj

PASS0_IA64_OBJECTS=

AMD64_OBJECTS= \
    $(_OBJ_DIR)\amd64\driverentry.obj \
    $(_OBJ_DIR)\amd64\stddcls.obj

PASS0_AMD64_OBJECTS=

ARM_OBJECTS= \
    $(_OBJ_DIR)\arm\driverentry.obj \
    $(_OBJ_DIR)\arm\stddcls.obj

PASS0_ARM_OBJECTS=

