/*

  Includes:

  Sizzle CSS Selector Engine
  Copyright 2011, The Dojo Foundation
  Released under the MIT, BSD, and GPL Licenses.
  More information: http://sizzlejs.com/
 VigLink JavaScript Library -- http://www.viglink.com

 Permission is hereby granted to create derivative works, but only for use
 with the VigLink web service.

 Copyright (c) 2013 VigLink. Rights reserved and patent(s) pending.
*/
(function(l){var e,b,m=function(c,j){try{return("function"===typeof window[j]||"object"===typeof window[j])&&c instanceof window[j]}catch(a){}return!1};b={_breaker:{},each:function(c,j){var a,d;if("object"===b.type(c)&&c.hasOwnProperty)for(a in c){if(c.hasOwnProperty(a)&&j(c[a],a)===b._breaker)break}else if(c){a=0;for(d=c.length;a<d&&j(c[a],a)!==b._breaker;a++);}},extend:function(c){var j,a,b,d,g=arguments.length;c=c||{};for(a=1;a<g;a++)if(d=arguments[a],void 0!==d&&null!==d)for(b in d)j=d[b],c!==
j&&void 0!==j&&(c[b]=j);return c},noop:function(){},type:function(c){return null===c?"null":void 0===c?"undefined":m(c,"HTMLElement")||"object"===typeof c&&1===c.nodeType&&"string"===typeof c.nodeName?"element":m(c,"HTMLDocument")||"object"===typeof c&&("defaultView"in c||"parentWindow"in c)?"document":c==c.window?"window":Object.prototype.toString.call(c).slice(8,-1).toLowerCase()}};b.extend(b,{addClass:function(c,j){b.hasClass(c,j)||(c.className=(c.className?c.className+" ":"")+j)},attrValues:function(c,
j,a){return(j=c[j])?j.split(a||" "):[]},bind:function(c,j){return function(){return c.apply(j,arguments)}},browser:function(){var c={},j,a=navigator.userAgent.toLowerCase().replace(/\s*[()]\s*/g,"; ").replace(/(\/[\w.]+)\s+/g,"$1; ").replace(/\;\s*$/,"").split(/;\s*/);b.each(a,function(a){j=(/[\/ :]([^\/ :]+)$/.exec(a)||[])[1];c[j?a.substr(0,a.length-j.length-1).replace(/\d*$/,""):a]=j||!0});return{aol:c.aol,blackberry:c.blackberry,ie:c.msie,ios:c.mobile&&c.safari,opera:c.opera,playstation:c.playstation,
version:parseFloat(c.version||c.crios)||!1}}(),cache:function(){var c={},j="vglnk_"+(new Date).getTime(),a=0;return function(b,d,g){if(b){var h=b[j];if(h||void 0!==g)return h||(h=++a),c[h]||(b[j]=h,c[h]={}),void 0!==g&&(c[h][d]=g),"string"===typeof d?c[h][d]:c[h]}}}(),canonicalizeHostname:function(c){"string"===typeof c&&(c=b.createA(c));return c.hostname?c.hostname.toString().toLowerCase().replace(/^www\./,"").replace(/:.*$/,""):""},clone:function(c){return b.extend({},c)},contains:function(c,j){return-1!==
b.indexOf(c,j)},context:function(c){"element"===b.type(c)&&(c=c.ownerDocument);"document"===b.type(c)&&(c=c.defaultView||c.parentWindow);if("window"===b.type(c))return c},containsPII:function(c){return/\b[A-Z0-9._%+-]+(?:%(?:25)*40|@)[A-Z0-9.-]+\.[A-Z]{2,4}\b/i.test(c)},contextIsAncestor:function(c,j){for(var a=c.self;a.parent&&a.parent!==a;)if(a=a.parent,a===j)return!0;return!1},cors:function(c){var j,a=function(){eval(j.responseText)};j=new window.XMLHttpRequest;j.onreadystatechange=function(){4===
j.readyState&&200===j.status&&a()};try{j.open("GET",c),j.withCredentials=!0,j.send()}catch(b){return!1}},createA:function(c,j){return b.createEl("a",{href:c,target:j})},createEl:function(c,j,a,d){var g;c=(d||document).createElement(c);j=j||{};a=a||{};for(g in j)void 0!==j[g]&&(c[g]=j[g]);b.css(c,a);return c},css:function(c,j){for(var a in j)try{c.style[a]=j[a]}catch(b){}return c},destructing:function(c){var j=!1,a;return function(){j||(a=c.apply(null,arguments),j=!0);return a}},escapeRegExp:function(){var c;
return function(j){c=c||RegExp("([.*+?^${}()|[\\]\\\\])","g");return j.replace(c,"\\$1")}}(),eventLink:function(c){var j,a=c.target||c.srcElement;do{try{j=a.nodeType}catch(b){break}if(1===j&&(c=a.tagName.toUpperCase(),"A"===c||"AREA"===c))return a;a=a.parentNode}while(a)},exceptionLogger:function(){var c=!1,j=b.noop;return function(a,b){if(void 0!==b)c=b,j=a;else return function(){if(c)try{return a.apply(this,arguments)}catch(b){j(b)}else return a.apply(this,arguments)}}}(),find:function(c,j){var a;
b.each(c,function(c,d){if(j(c,d))return a=c,b._breaker});return a},generateNodeFilter:function(){var c=function(c,j){var a,b;j=","+j.join(",")+",";a=0;for(b=c.length;a<b;a++)if(-1!==j.indexOf(","+c[a]+","))return!0;return!1},j=function(c,j){var a=c.nodeName.toLowerCase();return-1!==j.indexOf(","+a+",")};return function(a){a=b.extend({custom:null,classes:[],rels:[],tags:[]},a);a.tags.length&&(a.tags=","+a.tags.join(",").toLowerCase()+",");return function(d,g){g=b.extend({ancestors:!0,self:!0},g);var h=
!0,e=!0,f=function(d,F){var g;if(g=!(a.tags.length&&j(d,a.tags))){if(g=a.classes.length){g=a.classes;var h=b.attrValues(d,"className");g=c(g,h)}if(g=!g){if(g=a.rels.length)g=a.rels,h=b.attrValues(d,"rel"),g=j(d,",a,")&&c(g,h);g=!g&&!("function"===b.type(a.custom)&&a.custom(d,F))}}return g},e=!g.self||f(d,!0);if(g.ancestors)for(;d.parentNode;)if(d=d.parentNode,1===d.nodeType&&!f(d,!1)){h=!1;break}return e&&h}}}(),fromQuery:function(c){"?"===c.substr(0,1)&&(c=c.substr(1));c=c.split("\x26");var a={};
b.each(c,function(c){c=c.split("\x3d");a[decodeURIComponent(c[0])]=decodeURIComponent(c[1])});return a},geometry:function(){var c,a=arguments.length,d=Infinity,g=Infinity,h=-Infinity,e=-Infinity,f;for(c=0;c<a;c++)f=b.position(arguments[c]),d=Math.min(d,f.x),g=Math.min(g,f.y),h=Math.max(h,f.x+arguments[c].offsetWidth),e=Math.max(e,f.y+arguments[c].offsetHeight);return{x:d,y:g,w:h-d,h:e-g,x1:d,y1:g,x2:h,y2:e}},getActualHref:function(c){return b.cache(c,"href")||c.href},hasAttrValue:function(c,a,d,g){return a?
b.contains(b.attrValues(c,a,g),d):!1},hasClass:function(c,a){return b.hasAttrValue(c,"className",a)},hasRel:function(c,a){return b.hasAttrValue(c,"rel",a)},indexOf:Array.prototype.indexOf?function(c,a){return Array.prototype.indexOf.call(c,a)}:function(c,a){var d,b;d=0;for(b=c.length;d<b;d++)if(c[d]===a)return d;return-1},isArray:function(c){return"array"===b.type(c)},isDefaultPrevented:function(c){return c.isDefaultPrevented&&c.isDefaultPrevented()||!1===c.returnValue||!0===c.defaultPrevented},jsonp:function(c){var a=
document.getElementsByTagName("script")[0];c=b.createEl("script",{type:"text/javascript",src:c});a.parentNode.insertBefore(c,a)},map:function(c,a){var d=[];b.each(c,function(c,b){void 0!==c&&(d[b]=a(c))});return d},matches:function(){try{return window.vglnk.Sizzle.matchesSelector.apply(window.vglnk.Sizzle,arguments)}catch(c){return!0}},on:function(){var c;return function(a,d,g){var h,e;if(1===arguments.length)c=a;else{if(2===arguments.length){if(!c)return;g=d;d=a;a=c}try{h=a["on"+d]}catch(f){}"function"===
typeof h&&(a["on"+d]=b.bind(function(c){c=c||window.event;var d=h.apply(a,arguments);this.exceptionLogger(function(){return c?(void 0!==d&&!1!==c.returnValue&&(c.returnValue=d),b.isDefaultPrevented(c)&&"function"===b.type(c.preventDefault)&&c.preventDefault(),c.returnValue):d})()},this));e=b.exceptionLogger(function(){if(c.enabled())return g.apply(null,arguments)});a.addEventListener?a.addEventListener(d,e,!1):a.attachEvent&&a.attachEvent("on"+d,e)}}}(),position:function(c){var a,d=0,b=0,g=0,h=0;
if(!c.offsetParent)return!1;a=c;do d+=a.offsetLeft,b+=a.offsetTop,a=a.offsetParent;while(a);a=c;do g+=a.scrollLeft,h+=a.scrollTop,a=a.parentNode;while(a&&a!==document.body);return{x:d-g,y:b-h}},preventDefault:function(c){c.preventDefault&&c.preventDefault();return c.returnValue=!1},ready:function(){var c=!1,a=[],d=!1,g,h,e,f,k;document.addEventListener?e=function(){document.removeEventListener("DOMContentLoaded",e,!1);k()}:document.attachEvent&&(f=function(){"complete"===document.readyState&&(document.detachEvent("onreadystatechange",
f),k())});g=function(){if(!c){c=!0;if("interactive"===document.readyState||"complete"===document.readyState)return k();if(document.addEventListener)document.addEventListener("DOMContentLoaded",e,!1);else if(document.attachEvent){document.attachEvent("onreadystatechange",f);var a=!1;try{a=null===window.frameElement}catch(j){}document.documentElement.doScroll&&a&&h()}b.on(window,"load",k)}};h=function(){if(!d){try{document.documentElement.doScroll("left")}catch(c){setTimeout(b.exceptionLogger(h),1);
return}k()}};k=function(){if(!d){if(!document.body)return setTimeout(b.exceptionLogger(k),13);d=!0;a&&(b.each(a,function(c){c()}),a=null)}};return function(c){g();d?c():a.push(c)}}(),reformatKeys:function(c){var a,d,g=function(c){return"_"+c.toLowerCase()};for(a in c)d=a.replace(/([A-Z])/g,g),"object"===b.type(c[a])&&(c[a]=b.reformatKeys(c[a])),d!==a&&(c[d]=c[a],delete c[a]);return c},removeClass:function(c,a){if(b.hasClass(c,a)){var d,g,h=b.attrValues(c,"className");d=0;for(g=h.length;d<g;d++)h[d]===
a&&delete h[d];c.className=h.join(" ")}},request:function(c,a,d){var g,h;d=b.extend({fn:b.noop,"return":!1,timeout:null},d);"string"===typeof d.fn?a=b.extend(a,{jsonp:d.fn}):"function"===typeof d.fn&&(g=b.destructing(d.fn),h=b.uniqid("vglnk_jsonp_"),a=b.extend(a,{jsonp:h}),window[h]=b.exceptionLogger(function(){g.apply(this,arguments);window[h]=void 0}),null!==d.timeout&&setTimeout(b.exceptionLogger(g),d.timeout));a=b.extend({format:"jsonp"},a);a=b.toQuery(a);c=c+(a.length?"?":"")+a;return d["return"]?
c:b.traits.cors&&!1!==b.cors(c)?!0:b.jsonp(c)},select:function(){try{return window.vglnk.Sizzle.apply(window,arguments)}catch(c){return[]}},toArray:function(c){if(c&&void 0!==c.length)try{return Array.prototype.slice.call(c,0)}catch(a){var d,b,g=[];d=0;for(b=c.length;d<b;d++)g[d]=c[d];return g}},toQuery:function(c){var a,d="";for(a in c)null!==c[a]&&void 0!==c[a]&&(d+="\x26"+encodeURIComponent(a)+"\x3d"+encodeURIComponent(c[a]));return d.substr(1)},transmitsPII:function(c){return b.containsPII(c+
" "+document.referrer)},updateUrl:function(c,a){return b.extend(b.createA(c),a).href},uniqid:function(){var c=0;return function(a){return(a||"")+(new Date).getTime()+c++}}()});b.traits={basicCompatibility:!(b.browser.blackberry||b.browser.playstation),cors:window.XMLHttpRequest&&void 0!==(new window.XMLHttpRequest).withCredentials,crossWindowCommunication:!b.browser.ios,jsRedirectSetsReferrer:b.browser.aol||!(b.browser.ie||b.browser.opera),quirksMode:!Boolean(window.addEventListener),windowLevelHandlers:Boolean(window.addEventListener)};
var t={bbp:{id_finder:["div",/^post-(\d+)$/],scope:"li .post"},hdlr:{id_finder:["div",/^post_(\d+)$/],scope:".post-content-area"},ipb:{id_finder:["div",/^post_id_(\d+)$/],scope:".post_body .post"},phpb:{id_finder:["div.post",/^p(\d+)$/],scope:".postbody .content,.postbody .signature"},ubb:{id_finder:["a",/^Post(\d+)$/,"name"],scope:".post_inner *[id^\x3d'body'],.post_inner .signature"},vb3:{id_finder:["div[id], table[id]",/^post(\d+)$/],scope:"td[id^\x3d'td_post_'] div[id^\x3d'post_message_'],td[id^\x3d'td_post_'] div[id^\x3d'post_message_'] ~ div:not([class])"},
vb4:{id_finder:["li",/^post_(\d+)$/],scope:".post-content,.postbody .content,.postbody .signature,ul.conversation-list .list-item-body"},wppr:{id_finder:["div",/^post-(\d+)$/],scope:null}};b.platform=function(c){return b.extend(t[c]||{},{getPostIDs:function(){var c=[],a=this.id_finder;a&&b.each(b.select(a[0]),function(d){var b=a[2]||"id";(d=d[b]?d[b].match(a[1]):null)&&c.push(d[1])});return c.length?c:null}})};var f,n,i,k=function(c){var a=c.previousSibling,d=c.nextSibling,g=["",c.textContent,""],
h=function(c,a){for(var d=c,j=d.data;(d=d[a+"Sibling"])&&3===d.nodeType;)j+=d.data;return j},f=function(c,a,d){c=c.replace(/\s+/g," ");a=a.replace(/\s+/g," ");d=d.replace(/\s+/g," ");c=c.replace(/^\s+/,"");" "===a.substr(0,1)&&(a=a.substr(1),c+=" "!==c.substr(c.length-1,1)?" ":"");" "===a.substr(a.length-1,1)&&(a=a.substr(0,a.length-1),d=(" "!==d.substr(0,1)?" ":"")+d);d=d.replace(/\s+$/,"");return[c,a,d]};void 0!==g[1]&&(g[0]=a&&3===a.nodeType?h(a,"previous"):"",g[2]=d&&3===d.nodeType?h(d,"next"):
"",g=f.apply(this,g),""!==g[0]&&""!==g[2]&&(g[0]=g[0].split(" ").reverse().slice(0,10+(" "===g[0].substr(g[0].length-1,1)?1:0)).reverse().join(" "),g[2]=g[2].split(" ").slice(0,10).join(" "),c={type:"context",itype:(b.cache(c,"params")||{}).type,before:g[0],after:g[2],txt:g[1],loc:location.href,out:b.getActualHref(c),v:2},e.log("info",b.toQuery(c))))},B={};b.harmony={UNSAFE_QUIRKSMODE_HANDLERS:0,LINK_LEVEL_EVENTS:-1};var s=b.exceptionLogger(function(){var c=!0===window.document.__v5k;window.document.__v5k=
!0;c||(this.initLibEvents(),this.initNamespace(),this.initOptions(),b.exceptionLogger(b.bind(this.logException,this),!f.dev),this.initProcessors(),this.initDRApi(),this.initApi(),this.enabled()&&(this.initLegacyCallbacks(),this.ping()))}),v=[],u,C=1,x={},y={product_widget:"spotlight"},w=function(){var c=!1,a={},d=function(c){return function(){if(c){var a=b.toArray(arguments);a.unshift("custom",c);e.log.apply(this,a)}}};u=null;b.each(x,function(g,h){h=y[h]||h;g.setup=g.setup||window.vglnk&&window.vglnk[h+
"_plugin"];g.setup?(!g.run&&"function"===b.type(g.setup)&&(g.run=g.setup(g.opts,b.clone(b),i,d(g.opts.key))||b.noop),g.opts.mode===e.PLUGIN_MANUAL?a[h]=g:g.run()):(c=!0,a[h]=g)});x=a;c&&(u=setTimeout(b.exceptionLogger(w),Math.min(Math.max(Math.pow(2,++C),100),5E3)))},r=function(c){return function(){delete x[c].opts.mode;C=1;clearTimeout(u);w()}},p=b.canonicalizeHostname(document.location),z=b.generateNodeFilter({rels:["norewrite","noskim"],custom:function(c){var a,d="";try{a=c.hostname,d=c.protocol,
a.charAt(0)}catch(g){return!0}""!==a&&(a=b.canonicalizeHostname(c));return""===a||p===a||!d.match(/^https?:$/i)||f.norewrite[a]||!(f.rewrite_original||b.cache(c,"type"))}}),o,E=!1,D={},a=!1,d=[],g=function(c){if(void 0===c)return d;"function"===b.type(c)&&(d.push({id:b.uniqid(),fn:c}),a&&this.initLinks())};g(function(){a=!0});e={PLUGIN_MANUAL:1,api:function(c,a,d){c=f.api_url+"/"+c;a=b.extend({cuid:f.cuid,key:f.key,drKey:f.key?null:f.dr_key,loc:location.href,subId:f.sub_id,v:1},a);a.subId&&a.key!==
f.key&&(a.subId=null);return b.request(c,a,d)},addEventListener:function(c,a){this.fire(c,a)},click:function(c,a){var d,g,h,e,i=b.context(c)||window;a=c.target||a;a=!a||a===i.name||"_top"===a&&i.top===i||"_parent"===a&&i.parent===i?"_self":a;"_self"===a?h=i:b.traits.crossWindowCommunication&&b.traits.jsRedirectSetsReferrer?(g=i.open("",a),g.focus(),h=g):h=void 0;if("_self"!==a&&(!b.traits.crossWindowCommunication||!b.traits.jsRedirectSetsReferrer))e="go";else try{if(void 0===h.document)throw!0;e=
"jsonp"}catch(r){e="go"}d=b.destructing(b.bind(function(){f.time_click&&arguments.length&&this.logTime("clk");var d=b.toArray(arguments);d.unshift(c,h,a);this.onApiClick.apply(this,d)},this));b.cache(this,"link","string"===typeof c?c:b.getActualHref(c));if("string"===typeof c&&(c=b.createA(c,a),!this.processLink(c))||!f.enabled)return d();g=this.clickParams(c,e);this.logTime();f.log_context&&k(c);if("go"===e)this.redirect(this.api("click",g,{"return":!0}),i,h,a);else if(h===i)this.api("click",g,{fn:d,
timeout:f.click_timeout});else{if(b.contextIsAncestor(i,h))return this.redirect(b.getActualHref(c),i,h,a);d=b.exceptionLogger(d);setTimeout(function(){d()},f.click_timeout);h.document.open();h.callback=d;h.document.write("\x3chtml\x3e\x3chead\x3e\x3ctitle\x3e"+b.getActualHref(c)+'\x3c/title\x3e\x3cscript type\x3d"text/javascript" src\x3d"'+this.api("click",g,{fn:"callback","return":!0})+'"\x3e\x3c/script\x3e\x3c/head\x3e\x3c/html\x3e');h.document.close()}},clickParams:function(c,a){var d=b.extend(b.cache(c,
"params"),{format:a,libId:f.library_id,out:b.getActualHref(c),ref:window.document.referrer||null,reaf:f.reaffiliate||null,title:window.document.title,txt:c.innerHTML});128<d.txt.length&&(d.txt=d.txt.replace(/<[^>]+>/g,""),d.txt=128<d.txt.length?d.txt.substr(0,125)+"...":d.txt);return d},enabled:function(){if(f.enabled&&n!==window&&window.vglnk&&(window.vglnk.key||"function"===typeof window.vglnk))f.enabled=!1;return f.enabled},expose:function(c,a){if(a=a||this[c])"function"===typeof a?a=b.exceptionLogger(b.bind(a,
this)):"object"===typeof a&&(a=b.clone(a)),i[c]||(i[c]=a)},fire:function(c,a){c=c.toLowerCase();var d=B[c]||{fired:!1,listeners:[]};"function"===typeof a?d.fired?a({type:c}):d.listeners.push(a):(d.fired=!0,b.each(d.listeners,function(a){"function"===typeof a&&a({type:c})}),d.listeners=[]);B[c]=d},handleRightClick:function(c,a){if(f.rewrite_modified&&c&&a)switch(a){case "setup":b.cache(c,"href")||b.cache(c,"href",c.href);c.href=this.api("click",this.clickParams(c,"go"),{"return":!0});setTimeout(b.exceptionLogger(b.bind(function(){this.handleRightClick(c,
"teardown")},this)),0);break;case "teardown":c.href=b.cache(c,"href"),b.cache(c,"href",null)}},harmony:function(c){return f.harmony_level<=c},init:s,initApi:function(){var c,a={};if(window.vglnk)for(c in window.vglnk)"_plugin"===c.substr(-7)&&(a[c]=window.vglnk[c]);i=n[l]=b.noop;this.expose("click");this.expose("link",function(c){"element"===b.type(c)&&c.href&&(e.initContext(b.context(c)),e.processLink(c))});this.expose("$",b.clone(b));this.expose("api");this.expose("opt");this.expose("registerProcessor",
function(){if(0<arguments.length)return e.registerProcessor.apply(e,arguments)});b.extend(i,i===window.vglnk?a:{})},initContext:function(c){if(void 0===c)return v;c&&!b.contains(v,c)&&(v.push(c),this.initLinks(c),this.initEvents(c))},initDRApi:function(){var c=!1;window.DrivingRevenue=b.exceptionLogger(b.destructing(b.bind(function(){c=!0;f.dr_key=window.DR_id;this.enabled()&&this.ping()},this)));b.on("DOMReady",function(){if(!c)try{delete window.DrivingRevenue}catch(a){window.DrivingRevenue=void 0}})},
initEvents:function(c){var a={left:e.onClick,right:e.onContextmenu},d={left:b.noop,right:b.noop},g=b.traits.windowLevelHandlers?c:c.document,h=function(g){g=g||c.event;if((g=b.eventLink(g))&&!b.cache(g,"evented"))f(g,e.harmony(b.harmony.LINK_LEVEL_EVENTS)?a:d),b.cache(g,"evented",!0)},f=function(c,a){b.on(c,"click",b.bind(a.left,e));b.on(c,"contextmenu",b.bind(a.right,e))};b.on(g,"copy",b.bind(e.onCopy,e));b.on(g,"mousedown",h);if(e.harmony(b.harmony.LINK_LEVEL_EVENTS))b.on("DOMReady",function(){b.each(c.document.links,
function(c){b.on(c,"mousedown",h)})});(!b.traits.quirksMode||e.harmony(b.harmony.UNSAFE_QUIRKSMODE_HANDLERS))&&f(g,a)},initLegacyOptions:function(){var c,a={DR_id:"dr_key",vglnk_api_key:"key",vglnk_cuid:"cuid",vglnk_domain:"api_url",vglnk_reaf:"reaffiliate",vglnk_subid:"sub_id"};for(c in a)void 0!==window[c]&&(i[a[c]]=window[c],"vglnk_domain"===c&&(i[a[c]]+="/api"))},initLegacyCallbacks:function(){var c,a={vl_cB:b.bind(this.onApiClick,this),vl_disable:function(){f.enabled=!1}};for(c in a)window[c]=
a[c]},initLibEvents:function(){b.on(e);b.ready(b.bind(function(){this.fire("DOMReady")},this))},initLinks:function(a){var d=b.bind(function(a){b.each(b.toArray(a.document.links),b.bind(this.processLink,this))},this);void 0===a?b.each(this.initContext(),d):d(a)},initNamespace:function(){window.vglnk&&window.vglnk.key&&(l="vglnk");var a=window,d=l.split("."),b;for(l=d.pop();0<d.length;)b=d.shift(),a[b]=a[b]||{},a=a[b];n=a;i=n[l]=n[l]||{}},initOptions:function(){var a;this.initLegacyOptions();f=b.extend(this.publicOptions({api_url:"//api.viglink.com/api",
asset_url:"//cdn.viglink.com/api",cuid:null,dev:!1,dr_key:null,enabled:b.traits.basicCompatibility,key:null,partner:null,sub_id:null,reaffiliate:!1,harmony_level:0,rewrite_original:!0,rewrite_modified:!1}),f,i,{click_timeout:1E3,hop_timeout:2E3,debug:!1,library_id:null,log_context:!0,nofollow:{},norewrite:{},plugins:{link_affiliation:{},modified_clicks:{},partner_integration:{}},time_click:!1,time_ping:!1,testing_js:[]});for(a in f)"_plugin"===a.substr(-7)&&delete f[a]},initPlugins:function(a){for(var d in a)"object"===
typeof a[d]&&!1!==a[d].enabled&&(x[d]={opts:a[d]},a[d].mode===this.PLUGIN_MANUAL&&this.expose("init_"+d,r(d)));w()},initProcessors:function(){this.registerProcessor(function(a){var d;d=b.createA(f.api_url);if("/api/click"===a.pathname&&(a.hostname===d.hostname||a.hostname.match(/(^|\.)(api|cdn|apicdn)\.viglink\.com$/)))d=b.fromQuery(a.search),void 0!==d.out&&(a.href=d.out,delete d.out,b.cache(a,"params",d))});this.registerProcessor(function(a){f.nofollow[a.href]&&!b.hasRel(a,"nofollow")&&(a.rel=(a.rel?
a.rel+" ":"")+"nofollow")});this.registerProcessor(function(a){window.IPBoard&&(window.IPBoard.prototype&&window.IPBoard.prototype.delegate&&b.hasRel(a,"external"))&&(a.rel=a.rel.replace(/(^| )external( |$)/,""),a.target="_blank")})},isRewritable:function(a){return z(a,{ancestors:!1})},log:function(a,d,g,h){var e,k=b.toQuery({nocache:b.uniqid()});e="pixel.gif";if("custom"===a)k+="\x26"+b.toQuery({key:d,type:g}),b.each("array"===b.type(h)?h:[h],function(a){b.each(["e","i","o"],function(c){delete a[c]});
k+="\x26"+b.toQuery(a)});else{k+="\x26"+b.toQuery({key:f.key,drKey:f.key?null:f.dr_key});if("time"===a)e="time.gif",a={libId:f.library_id,time:g,type:d};else if("exception"===a)a={e:d,o:g};else if("info"===a)a={i:d};else return;k+="\x26"+b.toQuery(a)}e=f.api_url+"/"+e+"?"+k;b.transmitsPII(e)||(b.createEl("img").src=e)},logException:function(a){if(f.debug){var d={link:b.cache(this,"link"),loc:document.location.href,UA:navigator.userAgent};"string"===typeof a?d.message=a:d=b.extend(d,a);this.log("exception",
a,b.toQuery(d))}},logTime:function(a){0===arguments.length?o=(new Date).getTime():this.log("time",a,(new Date).getTime()-o)},onApiClick:function(a,d,g,h,e){var k=h||b.getActualHref(a),i=b.bind(function(){this.redirect(k,b.context(a),d,g)},this);"object"===typeof e&&(e.tracking||e.image)?(h=b.createEl(e.tracking?"iframe":"img",{src:e.tracking||e.image},{height:0,width:0,visibility:"hidden"}),document.body.appendChild(h),setTimeout(b.exceptionLogger(i),e.timeout||f.hop_timeout)):i()},onApiPing:function(a,
d,g,h,k,i){f.rewrite_original=!1;k=b.reformatKeys(k||{});var r,l;h=function(a){var c={},d=function(a){b.isArray(a)?c[a[0]]=a[1]:c[a]=1};b.isArray(a)&&b.each(a,d);return c};l=b.extend(f.plugins,k.plugins);f=b.extend(f,k);delete f.plugins;f.library_id=a;f.click_timeout=d;f.time_ping&&this.logTime("png");"array"===b.type(f.testing_js)&&0<f.testing_js.length&&b.each(f.testing_js,function(a){b.jsonp(a)});b.extend(f.norewrite,h(g));b.extend(f.nofollow,h(i));for(r in f)"on"===r.toLowerCase().substr(0,2)&&
(2<r.length&&"function"===b.type(f[r]))&&(b.on(e,r.toLowerCase().substr(2),b.bind(f[r],window)),delete f[r]);this.initPlugins(l);this.initContext(window);this.fire("libready")},onClick:function(a){a=a||window.event;var d=a.ctrlKey||a.metaKey||a.altKey||a.shiftKey,g=a.which&&1===a.which||0===a.button,h=b.eventLink(a);if(h&&this.isRewritable(h)&&!d&&g&&!b.isDefaultPrevented(a))return this.click(h),b.preventDefault(a)},onContextmenu:function(a){(a=b.eventLink(a||window.event))&&this.isRewritable(a)&&
this.handleRightClick(a,"setup")},onCopy:function(){var a,d,g,h,f=[];if(window.getSelection){g=window.getSelection();a=0;for(d=g.rangeCount;a<d;a++){try{h=g.getRangeAt(a).toString().replace(/((^)\s+|\s+$|\r)/g,"").replace(/\s*\n\s*/g,"\n")}catch(k){}0<h.length&&128>=h.length&&f.push(h)}}b.each(f,function(a){e.log("info",b.toQuery({type:"selection",txt:a,loc:location.href}))})},opt:function(a,d){void 0!==d&&void 0!==this.publicOptions()[a]&&(f[a]=d);return f[a]},ping:function(){if(!E&&(f.key||f.dr_key)){var a=
{ref:document.referrer||null};E=!0;b.transmitsPII(this.api("ping",a,{"return":!0}))||(this.logTime(),this.api("ping",a,{fn:b.bind(this.onApiPing,this)}))}},processLink:function(a){if(this.isRewritable(a)){var d=b.cache(a,"processors")||{};b.each(this.registerProcessor(),function(g){d[g.id]||g.fn(a);d[g.id]=!0});b.cache(a,"processors",d);return a}},publicOptions:function(a){"object"===b.type(a)&&(D=a);return b.extend({},D)},redirect:function(a,d,g,h){!b.traits.crossWindowCommunication&&!g?(h=d.open(a,
h),h.focus()):b.traits.jsRedirectSetsReferrer?setTimeout(b.exceptionLogger(function(){!g||g===d?d.location=a:b.contextIsAncestor(d,g)?g.location=a:g.location.replace(a)}),0):("_blank"===h&&(h=b.uniqid("win_")),h=b.createA(a,h),h.rel="norewrite",d.document.body.appendChild(h),h.click(),h.parentNode.removeChild(h))},registerProcessor:g};e.init();try{delete window.vglnk_self}catch(h){}})("undefined"===typeof vglnk_self?"vglnk":vglnk_self);window.vglnk=window.vglnk||{};
window.vglnk.link_affiliation_plugin=function(l,e,b){return function(){b.opt("rewrite_original",!0)}};window.vglnk=window.vglnk||{};window.vglnk.modified_clicks_plugin=function(l,e,b){return function(){b.opt("rewrite_modified",!0)}};window.vglnk=window.vglnk||{};
window.vglnk.dr_search_box_plugin=function(l,e,b){l=e.extend({key:null},l);var m={init:function(){e.each(this.getDRSearchForms(),function(b){if(!e.cache(b,"evented")){var f=m.getInput(b),l=function(){f.value||e.css(f,{"background-image":"url(http://cdn.viglink.com/images/ebay_watermark.gif)"})};e.cache(b,"evented",!0);b.onsubmit=null;f.onfocus=null;f.onblur=null;e.on(f,"focus",function(){e.css(f,{"background-image":"none"})});e.on(f,"blur",l);l();e.on(b,"submit",function(e){m.onSubmit(e,b)})}})},
getDRSearchForms:function(){var b=[];e.each(document.getElementsByTagName("form"),function(e){m.getInput(e)&&e.id.match(/^DR-ebay-search(CSS|2)?$/i)&&b.push(e)});return b},getInput:function(b){return b.p||b.q2},onSubmit:function(t,f){t=t||window.event;var n="http://shop.ebay.com/i.html?"+e.toQuery({_nkw:m.getInput(f).value}),n=e.createA(n,"_blank");e.cache(n,"params",{key:l.key});b.click(n);return e.preventDefault(t)}};return function(){l.key&&(m.init(),e.on("DOMReady",e.bind(m.init,m)))}};
window.vglnk=window.vglnk||{};
window.vglnk.link_optimization_plugin=function(l,e,b){var m,t={};l=e.extend({platform:null},l);var f=function(b){var f=b.textContent||b.innerText;b=e.canonicalizeHostname(b);f=e.createEl("a",{href:f});return e.canonicalizeHostname(f)===b},n=e.generateNodeFilter({classes:["nooptimize"],rels:["nooptimize"],custom:function(b,f){return f?Boolean(e.cache(b,"type")):!1}}),i={data:!1,timing:!1};m={getLinks:function(){var f=e.platform(l.platform).getPostIDs();b.api("optimize",{pt:l.platform,i:f?f.join("|"):
null,u:location.href},{fn:e.bind(m.onOptimizeApi,m)})},onOptimizeApi:function(b){"object"===e.type(b)&&"object"===e.type(b.optLinks)&&(t=b.optLinks,this.optimizeLinks({data:!0}))},optimizeLink:function(b){var i=t[b.href];if(i&&n(b)){var l=b.textContent||b.innerText,m;if(!(m=b.href===l))f(b)?(m=e.fromQuery(b.search),m=e.find(m,function(b){return b===l})):m=!1;if(m){m=i.optLink;for(var u;u=b.firstChild;)b.removeChild(u);b.appendChild(document.createTextNode(m))}else if(f(b))return;e.cache(b,"params",
{type:"LO",origOutId:i.pcid+":"+i.linkId});b.href=i.optLink}},optimizeLinks:function(f){i=e.extend(i,f);i.timing&&(i.data&&t)&&b.registerProcessor(e.bind(this.optimizeLink,m))},setup:function(){if(!l.platform||"full"===l.platform)this.getLinks();else e.on("DOMReady",e.bind(this.getLinks,this))}};m.setup();return function(){e.on("DOMReady",function(){m.optimizeLinks({timing:!0})})}};window.vglnk=window.vglnk||{};
window.vglnk.page_harmony_plugin=function(l,e,b){l=e.extend({level:null},l);return function(){var e=parseInt(l.level,10);isFinite(e)&&b.opt("harmony_level",e)}};window.vglnk=window.vglnk||{};
window.vglnk.partner_integration_plugin=function(l,e){var b="https:"===document.location.protocol,m={setup:function(){window._comscore=window._comscore||[]},run:function(){var l=window._comscore;l&&"function"===e.type(l.push)&&(l.push({c1:8,c2:17570528,c3:1}),e.jsonp("//"+(b?"sb":"b")+".scorecardresearch.com/beacon.js"))}};m.setup();return function(){m.run()}};window.vglnk=window.vglnk||{};
window.vglnk.product_linker_plugin=function(l,e,b,m){var t,f,n=null,i={},k,B=0,s=0,v=0,u=0;l=e.extend({cat:null,platform:null,key:null,link_phrases:!0,link_urls:!0,link_target:null,per_page:null,per_phrase:5,product_source:null,proximity:null,same_proximity:100,scope:null,type:null,ui:!0},l);if(l.key){t=e.platform(l.platform);var C={data:l.link_phrases?!1:l.link_urls,timing:!1},x=function(b){var p=!1,m=b.parentNode;b.data&&(p=k.test(b.data.replace(/\s+/," ")));if(p)for(var o=b,n,t,a,p=function(a,
c){var d,b,g,h,j,f,k,A,r,p,o=function(c){r.parentNode.insertBefore(a,r);r.parentNode.removeChild(r);return c};r=e.createEl("span");a.parentNode.insertBefore(r,a);r.appendChild(a);p=e.geometry(r);if(l.proximity||l.same_proximity)for(f in i)if((k=i[f].links)&&!(i[f]===c&&!l.same_proximity||i[f]!==c&&!l.proximity)){A=i[f]===c?Math.max(l.same_proximity,l.proximity):l.proximity;d=0;for(b=k.length;d<b;d++){j=k[d].segments;g=0;for(h=j.length;g<h;g++){var m=j[g].geometry,n=p,z=A,m=e.extend({},m);m.x1-=z;
m.y1-=z;m.x2+=z;m.y2+=z;if(m.x1<n.x2&&m.x2>n.x1&&m.y1<n.y2&&m.y2>n.y1)return o(!1)}}}return o(!0)};o&&o.data&&(Boolean(t=o.data.match(/^\s+/))||Boolean(t=o.data.match(k)));){n=t[0];a=t.slice(1).join("");b=i[a.toLowerCase()];n=o.data.indexOf(n)+n.length-a.length;0<n&&(o=o.splitText(n));n=o.length<=a.length?null:o.splitText(a.length);a&&!b&&(b={url:a.match(/^https?:\/\//i)?a:"http://"+a,type:"U"});var d;if(d=a){var g=d=void 0;d=!b||!l.per_phrase||!b.count||b.count<l.per_phrase;g=!l.per_page||B<l.per_page;
d=d&&g&&p(o,b)}if(d&&(d=b,g=void 0,g=e.createEl("a"),g.innerHTML=a.replace(/([a-z0-9]+ *|[^a-z0-9]+)/ig,"\x3cspan\x3e$1\x3c/span\x3e"),g.className="vglnk",e.cache(g,"type","inserted"),e.cache(g,"phrase",a),l.ui&&(g.title="Link added by VigLink"),f.initLink(g,d),a=g,!e.cache(a,"unlinked"))){"U"===b.type?u++:"L"===b.type.toUpperCase()?s++:v++;m.insertBefore(a,o);m.removeChild(o);var o=b,h=g=d=void 0,c=void 0,j={el:a,segments:[]};a=a.getElementsByTagName("span");var A={els:[]};d=0;for(g=a.length;d<g;d++)h=
a[d],void 0===c||h.offsetTop===c.offsetTop?A.els.push(h):(j.segments.push(A),A={els:[h]}),c=h;A.geometry=e.geometry.apply(e,A.els);j.segments.push(A);o.links=o.links||[];o.links.push(j);b.count++;B++}o=n}},y=e.generateNodeFilter({classes:["nolinks","atma-nolink","atma-nolinks"],tags:"applet embed object head img input link map meta param select button iframe option script style svg textarea title".split(" "),custom:function(b){return e.matches(b,"a[href]")}}),w=function(b){var f;if(b){if(y(b,{ancestors:!1,
self:!0}))for(f=b.firstChild;f;)b=f.nextSibling,1===f.nodeType?w(f):3===f.nodeType&&x(f),f=b}else e.each(e.select(l.scope),function(b){y(b,{ancestors:!0,self:!1})&&w(b)})};f={addPhrasesToMatcher:function(b){var f="";"regexp"===e.type(b)?f=b.source:"array"===e.type(b)&&(f="(?:^|[\\s\"'\\(])("+e.map(b,e.escapeRegExp).join("|")+")(?\x3d\\s|\\W*$|\\W{2})");""!==f&&(k=RegExp(k?"(?:"+f+"|"+k.source+")":f,"i"))},focusLink:function(b){b.id||(b.id=e.uniqid("vl-link-"));location.href.hash="#"+b.id;window.scrollBy(0,
-150)},getPhrases:function(){var i=t.getPostIDs();b.api("insert",e.extend(f.getPartnerParams(),{cat:l.cat,mode:l.mode,pt:l.platform,ps:l.product_source,i:i?i.join("|"):null,u:location.href,type:l.type}),{fn:e.bind(f.onInsertApi,f)})},getPartnerParams:function(){var e,f,i=b.opt("partner"),k={};for(e in i)break;if(e)for(f in i[e])k[e+"_"+f]=i[e][f];return k},initLink:function(f,i,k){if(k=l.link_target||k)f.target=k;f.rel="nofollow";f.href||(f.href=i.url);e.cache(f,"params",{exp:n,key:l.key,mid:i.mid,
type:i.type||null});e.cache(f,"href",f.href);b.link(f)},insertLinks:function(b){C=e.extend(C,b);C.timing&&(C.data&&k)&&(w(),f.log())},loadPhrases:function(b){var e,f,k,l=[];e=0;for(f=b.length;e<f;e++)k=b[e],k.phrase&&k.url&&(k.phrase=k.phrase.toLowerCase(),i[k.phrase]||(l.push(k.phrase),i[k.phrase]={count:i[k.phrase]?i[k.phrase].count:0,phrase:k.phrase,mid:k.mid,url:k.url,type:k.type||""}));0<l.length&&this.addPhrasesToMatcher(l);this.insertLinks({data:!0})},log:function(){var b,e,f={heavy:[],lite:[]},
k=function(b,e){return e.split(",")[0]-b.split(",")[0]};for(b in i)e=parseInt(i[b].count,10),0<e&&(e=[e,b.replace(/\|/g,"%7C")].join(),f["L"===i[b].type.toUpperCase()?"lite":"heavy"].push(e));f.lite.sort(k);f.heavy.sort(k);m("insert",[{ct:B,cl:s,ch:v,cu:u,exp:n},{pl:f.lite.join("|")},{ph:f.heavy.join("|")}])},onInsertApi:function(b){"object"===e.type(b)&&(n=b.exp,b.results&&this.loadPhrases(b.results))},setup:function(){l.scope=l.scope||t.scope||"body";l.link_urls&&this.addPhrasesToMatcher(RegExp("(?:(?:\\b(https?://)|(?:^|\\s)\\W*(www\\d{0,3}\\.|(?:[a-z0-9-]+\\.)+[a-z]{2,4}/))((?:[^\\s()\x3c\x3e]+|\\((?:[^\\s()\x3c\x3e]|(?:\\([^\\s()\x3c\x3e]+\\)))*\\))+(?:\\((?:[^\\s()\x3c\x3e]|(?:\\([^\\s()\x3c\x3e]+\\)))*\\)|[^\\s`!()\\[\\]{};:'\".,\x3c\x3e?\u00ab\u00bb\u201c\u201d\u2018\u2019]))|(?:^|\\s)\\W*((?:[a-z0-9-]+\\.)+com(?:/|\\b)))",
"i"));if(l.link_phrases)if(!l.platform||"full"===l.platform)this.getPhrases();else e.on("DOMReady",e.bind(this.getPhrases,this))}};f.setup();return function(){e.on("DOMReady",function(){f.insertLinks({timing:!0})})}}};window.vglnk=window.vglnk||{};window.vglnk.spotlight_plugin=function(l,e,b){window.vglnk.spotlight_plugin.exports={$:e,opts:l,vglnk:b};return function(){(!e.browser.ie||6<e.browser.version)&&e.jsonp(b.opt("asset_url")+"/spotlight.js")}};
(function(){function l(a,d,b,h,c,j){c=0;for(var e=h.length;c<e;c++){var f=h[c];if(f){for(var i=!1,f=f[a];f;){if(f.sizcache===b){i=h[f.sizset];break}1===f.nodeType&&!j&&(f.sizcache=b,f.sizset=c);if(f.nodeName.toLowerCase()===d){i=f;break}f=f[a]}h[c]=i}}}function e(a,d,b,h,c,j){c=0;for(var f=h.length;c<f;c++){var e=h[c];if(e){for(var k=!1,e=e[a];e;){if(e.sizcache===b){k=h[e.sizset];break}if(1===e.nodeType)if(j||(e.sizcache=b,e.sizset=c),"string"!==typeof d){if(e===d){k=!0;break}}else if(0<i.filter(d,
[e]).length){k=e;break}e=e[a]}h[c]=k}}}var b=/((?:\((?:\([^()]+\)|[^()]+)+\)|\[(?:\[[^\[\]]*\]|['"][^'"]*['"]|[^\[\]'"]+)+\]|\\.|[^ >+~,(\[\\]+)+|[>+~])(\s*,\s*)?((?:.|\r|\n)*)/g,m=0,t=Object.prototype.toString,f=!1,n=!0;[0,0].sort(function(){n=!1;return 0});var i=function(a,d,g,h){g=g||[];var c=d=d||document;if(1!==d.nodeType&&9!==d.nodeType)return[];if(!a||"string"!==typeof a)return g;var j,e,f,l,m,n=!0,o=i.isXML(d),q=[],p=a;do if(b.exec(""),j=b.exec(p))if(p=j[3],q.push(j[1]),j[2]){l=j[3];break}while(j);
if(1<q.length&&B.exec(a))if(2===q.length&&k.relative[q[0]])e=D(q[0]+q[1],d);else for(e=k.relative[q[0]]?[d]:i(q.shift(),d);q.length;)a=q.shift(),k.relative[a]&&(a+=q.shift()),e=D(a,e);else if(!h&&(1<q.length&&9===d.nodeType&&!o&&k.match.ID.test(q[0])&&!k.match.ID.test(q[q.length-1]))&&(j=i.find(q.shift(),d,o),d=j.expr?i.filter(j.expr,j.set)[0]:j.set[0]),d){j=h?{expr:q.pop(),set:u(h)}:i.find(q.pop(),1===q.length&&("~"===q[0]||"+"===q[0])&&d.parentNode?d.parentNode:d,o);e=j.expr?i.filter(j.expr,j.set):
j.set;for(0<q.length?f=u(e):n=!1;q.length;)j=m=q.pop(),k.relative[m]?j=q.pop():m="",null==j&&(j=d),k.relative[m](f,j,o)}else f=[];f||(f=e);f||i.error(m||a);if("[object Array]"===t.call(f))if(n)if(d&&1===d.nodeType)for(a=0;null!=f[a];a++)f[a]&&(!0===f[a]||1===f[a].nodeType&&i.contains(d,f[a]))&&g.push(e[a]);else for(a=0;null!=f[a];a++)f[a]&&1===f[a].nodeType&&g.push(e[a]);else g.push.apply(g,f);else u(f,g);l&&(i(l,c,g,h),i.uniqueSort(g));return g};i.uniqueSort=function(a){if(x&&(f=n,a.sort(x),f))for(var d=
1;d<a.length;d++)a[d]===a[d-1]&&a.splice(d--,1);return a};i.matches=function(a,d){return i(a,null,null,d)};i.matchesSelector=function(a,d){return 0<i(d,null,null,[a]).length};i.find=function(a,d,b){var h;if(!a)return[];for(var c=0,f=k.order.length;c<f;c++){var e,i=k.order[c];if(e=k.leftMatch[i].exec(a)){var l=e[1];e.splice(1,1);if("\\"!==l.substr(l.length-1)&&(e[1]=(e[1]||"").replace(/\\/g,""),h=k.find[i](e,d,b),null!=h)){a=a.replace(k.match[i],"");break}}}h||(h="undefined"!==typeof d.getElementsByTagName?
d.getElementsByTagName("*"):[]);return{set:h,expr:a}};i.filter=function(a,d,b,h){for(var c,e,f=a,l=[],m=d,n=d&&d[0]&&i.isXML(d[0]);a&&d.length;){for(var o in k.filter)if(null!=(c=k.leftMatch[o].exec(a))&&c[2]){var p,q,s=k.filter[o];q=c[1];e=!1;c.splice(1,1);if("\\"!==q.substr(q.length-1)){m===l&&(l=[]);if(k.preFilter[o])if(c=k.preFilter[o](c,m,b,l,h,n)){if(!0===c)continue}else e=p=!0;if(c)for(var r=0;null!=(q=m[r]);r++)if(q){p=s(q,c,r,m);var t=h^!!p;b&&null!=p?t?e=!0:m[r]=!1:t&&(l.push(q),e=!0)}if(void 0!==
p){b||(m=l);a=a.replace(k.match[o],"");if(!e)return[];break}}}if(a===f)if(null==e)i.error(a);else break;f=a}return m};i.error=function(a){throw"Syntax error, unrecognized expression: "+a;};var k=i.selectors={order:["ID","NAME","TAG"],match:{ID:/#((?:[\w\u00c0-\uFFFF\-]|\\.)+)/,CLASS:/\.((?:[\w\u00c0-\uFFFF\-]|\\.)+)/,NAME:/\[name=['"]*((?:[\w\u00c0-\uFFFF\-]|\\.)+)['"]*\]/,ATTR:/\[\s*((?:[\w\u00c0-\uFFFF\-]|\\.)+)\s*(?:(\S?=)\s*(?:(['"])(.*?)\3|(#?(?:[\w\u00c0-\uFFFF\-]|\\.)*)|)|)\s*\]/,TAG:/^((?:[\w\u00c0-\uFFFF\*\-]|\\.)+)/,
CHILD:/:(only|nth|last|first)-child(?:\(\s*(even|odd|(?:[+\-]?\d+|(?:[+\-]?\d*)?n\s*(?:[+\-]\s*\d+)?))\s*\))?/,POS:/:(nth|eq|gt|lt|first|last|even|odd)(?:\((\d*)\))?(?=[^\-]|$)/,PSEUDO:/:((?:[\w\u00c0-\uFFFF\-]|\\.)+)(?:\((['"]?)((?:\([^\)]+\)|[^\(\)]*)+)\2\))?/},leftMatch:{},attrMap:{"class":"className","for":"htmlFor"},attrHandle:{href:function(a){return a.getAttribute("href")}},relative:{"+":function(a,d){var b="string"===typeof d,h=b&&!/\W/.test(d),b=b&&!h;h&&(d=d.toLowerCase());for(var h=0,c=
a.length,e;h<c;h++)if(e=a[h]){for(;(e=e.previousSibling)&&1!==e.nodeType;);a[h]=b||e&&e.nodeName.toLowerCase()===d?e||!1:e===d}b&&i.filter(d,a,!0)},"\x3e":function(a,d){var b,h="string"===typeof d,c=0,e=a.length;if(h&&!/\W/.test(d))for(d=d.toLowerCase();c<e;c++){if(b=a[c])b=b.parentNode,a[c]=b.nodeName.toLowerCase()===d?b:!1}else{for(;c<e;c++)(b=a[c])&&(a[c]=h?b.parentNode:b.parentNode===d);h&&i.filter(d,a,!0)}},"":function(a,d,b){var h,c=m++,f=e;"string"===typeof d&&!/\W/.test(d)&&(h=d=d.toLowerCase(),
f=l);f("parentNode",d,c,a,h,b)},"~":function(a,d,b){var h,c=m++,f=e;"string"===typeof d&&!/\W/.test(d)&&(h=d=d.toLowerCase(),f=l);f("previousSibling",d,c,a,h,b)}},find:{ID:function(a,d,b){if("undefined"!==typeof d.getElementById&&!b)return(a=d.getElementById(a[1]))&&a.parentNode?[a]:[]},NAME:function(a,d){if("undefined"!==typeof d.getElementsByName){for(var b=[],h=d.getElementsByName(a[1]),c=0,e=h.length;c<e;c++)h[c].getAttribute("name")===a[1]&&b.push(h[c]);return 0===b.length?null:b}},TAG:function(a,
d){if("undefined"!==typeof d.getElementsByTagName)return d.getElementsByTagName(a[1])}},preFilter:{CLASS:function(a,d,b,h,c,e){a=" "+a[1].replace(/\\/g,"")+" ";if(e)return a;e=0;for(var f;null!=(f=d[e]);e++)f&&(c^(f.className&&0<=(" "+f.className+" ").replace(/[\t\n\r]/g," ").indexOf(a))?b||h.push(f):b&&(d[e]=!1));return!1},ID:function(a){return a[1].replace(/\\/g,"")},TAG:function(a){return a[1].toLowerCase()},CHILD:function(a){if("nth"===a[1]){a[2]||i.error(a[0]);a[2]=a[2].replace(/^\+|\s*/g,"");
var d=/(-?)(\d*)(?:n([+\-]?\d*))?/.exec("even"===a[2]&&"2n"||"odd"===a[2]&&"2n+1"||!/\D/.test(a[2])&&"0n+"+a[2]||a[2]);a[2]=d[1]+(d[2]||1)-0;a[3]=d[3]-0}else a[2]&&i.error(a[0]);a[0]=m++;return a},ATTR:function(a,d,b,e,c,f){d=a[1]=a[1].replace(/\\/g,"");!f&&k.attrMap[d]&&(a[1]=k.attrMap[d]);a[4]=(a[4]||a[5]||"").replace(/\\/g,"");"~\x3d"===a[2]&&(a[4]=" "+a[4]+" ");return a},PSEUDO:function(a,d,g,e,c){if("not"===a[1])if(1<(b.exec(a[3])||"").length||/^\w/.test(a[3]))a[3]=i(a[3],null,null,d);else return a=
i.filter(a[3],d,g,1^c),g||e.push.apply(e,a),!1;else if(k.match.POS.test(a[0])||k.match.CHILD.test(a[0]))return!0;return a},POS:function(a){a.unshift(!0);return a}},filters:{enabled:function(a){return!1===a.disabled&&"hidden"!==a.type},disabled:function(a){return!0===a.disabled},checked:function(a){return!0===a.checked},selected:function(a){return!0===a.selected},parent:function(a){return!!a.firstChild},empty:function(a){return!a.firstChild},has:function(a,d,b){return!!i(b[3],a).length},header:function(a){return/h\d/i.test(a.nodeName)},
text:function(a){return"text"===a.type},radio:function(a){return"radio"===a.type},checkbox:function(a){return"checkbox"===a.type},file:function(a){return"file"===a.type},password:function(a){return"password"===a.type},submit:function(a){return"submit"===a.type},image:function(a){return"image"===a.type},reset:function(a){return"reset"===a.type},button:function(a){return"button"===a.type||"button"===a.nodeName.toLowerCase()},input:function(a){return/input|select|textarea|button/i.test(a.nodeName)}},
setFilters:{first:function(a,d){return 0===d},last:function(a,d,b,e){return d===e.length-1},even:function(a,d){return 0===d%2},odd:function(a,d){return 1===d%2},lt:function(a,d,b){return d<b[3]-0},gt:function(a,d,b){return d>b[3]-0},nth:function(a,d,b){return b[3]-0===d},eq:function(a,d,b){return b[3]-0===d}},filter:{PSEUDO:function(a,d,b,e){var c=d[1],f=k.filters[c];if(f)return f(a,b,d,e);if("contains"===c)return 0<=(a.textContent||a.innerText||i.getText([a])||"").indexOf(d[3]);if("not"===c){d=d[3];
b=0;for(e=d.length;b<e;b++)if(d[b]===a)return!1;return!0}i.error(c)},CHILD:function(a,d){var b=d[1],e=a;switch(b){case "only":case "first":for(;e=e.previousSibling;)if(1===e.nodeType)return!1;if("first"===b)return!0;e=a;case "last":for(;e=e.nextSibling;)if(1===e.nodeType)return!1;return!0;case "nth":var b=d[2],c=d[3];if(1===b&&0===c)return!0;var f=d[0],i=a.parentNode;if(i&&(i.sizcache!==f||!a.nodeIndex)){for(var k=0,e=i.firstChild;e;e=e.nextSibling)1===e.nodeType&&(e.nodeIndex=++k);i.sizcache=f}e=
a.nodeIndex-c;return 0===b?0===e:0===e%b&&0<=e/b}},ID:function(a,d){return 1===a.nodeType&&a.getAttribute("id")===d},TAG:function(a,d){return"*"===d&&1===a.nodeType||a.nodeName.toLowerCase()===d},CLASS:function(a,d){return-1<(" "+(a.className||a.getAttribute("class"))+" ").indexOf(d)},ATTR:function(a,d){var b=d[1],b=k.attrHandle[b]?k.attrHandle[b](a):null!=a[b]?a[b]:a.getAttribute(b),e=b+"",c=d[2],f=d[4];return null==b?"!\x3d"===c:"\x3d"===c?e===f:"*\x3d"===c?0<=e.indexOf(f):"~\x3d"===c?0<=(" "+e+
" ").indexOf(f):!f?e&&!1!==b:"!\x3d"===c?e!==f:"^\x3d"===c?0===e.indexOf(f):"$\x3d"===c?e.substr(e.length-f.length)===f:"|\x3d"===c?e===f||e.substr(0,f.length+1)===f+"-":!1},POS:function(a,b,e,f){var c=k.setFilters[b[2]];if(c)return c(a,e,b,f)}}},B=k.match.POS,s=function(a,b){return"\\"+(b-0+1)},v;for(v in k.match)k.match[v]=RegExp(k.match[v].source+/(?![^\[]*\])(?![^\(]*\))/.source),k.leftMatch[v]=RegExp(/(^(?:.|\r|\n)*?)/.source+k.match[v].source.replace(/\\(\d+)/g,s));var u=function(a,b){a=Array.prototype.slice.call(a,
0);return b?(b.push.apply(b,a),b):a};try{Array.prototype.slice.call(document.documentElement.childNodes,0)}catch(C){u=function(a,b){var e=0,f=b||[];if("[object Array]"===t.call(a))Array.prototype.push.apply(f,a);else if("number"===typeof a.length)for(var c=a.length;e<c;e++)f.push(a[e]);else for(;a[e];e++)f.push(a[e]);return f}}var x,y;document.documentElement.compareDocumentPosition?x=function(a,b){return a===b?(f=!0,0):!a.compareDocumentPosition||!b.compareDocumentPosition?a.compareDocumentPosition?
-1:1:a.compareDocumentPosition(b)&4?-1:1}:(x=function(a,b){var e,h,c=[],j=[];e=a.parentNode;h=b.parentNode;var i=e;if(a===b)return f=!0,0;if(e===h)return y(a,b);if(e){if(!h)return 1}else return-1;for(;i;)c.unshift(i),i=i.parentNode;for(i=h;i;)j.unshift(i),i=i.parentNode;e=c.length;h=j.length;for(i=0;i<e&&i<h;i++)if(c[i]!==j[i])return y(c[i],j[i]);return i===e?y(a,j[i],-1):y(c[i],b,1)},y=function(a,b,e){if(a===b)return e;for(a=a.nextSibling;a;){if(a===b)return-1;a=a.nextSibling}return 1});i.getText=
function(a){for(var b="",e,f=0;a[f];f++)e=a[f],3===e.nodeType||4===e.nodeType?b+=e.nodeValue:8!==e.nodeType&&(b+=i.getText(e.childNodes));return b};s=document.createElement("div");v="script"+(new Date).getTime();var w=document.documentElement;s.innerHTML="\x3ca name\x3d'"+v+"'/\x3e";w.insertBefore(s,w.firstChild);document.getElementById(v)&&(k.find.ID=function(a,b,e){if("undefined"!==typeof b.getElementById&&!e)return(b=b.getElementById(a[1]))?b.id===a[1]||"undefined"!==typeof b.getAttributeNode&&
b.getAttributeNode("id").nodeValue===a[1]?[b]:void 0:[]},k.filter.ID=function(a,b){var e="undefined"!==typeof a.getAttributeNode&&a.getAttributeNode("id");return 1===a.nodeType&&e&&e.nodeValue===b});w.removeChild(s);w=s=null;s=document.createElement("div");s.appendChild(document.createComment(""));0<s.getElementsByTagName("*").length&&(k.find.TAG=function(a,b){var e=b.getElementsByTagName(a[1]);if("*"===a[1]){for(var f=[],c=0;e[c];c++)1===e[c].nodeType&&f.push(e[c]);e=f}return e});s.innerHTML="\x3ca href\x3d'#'\x3e\x3c/a\x3e";
s.firstChild&&("undefined"!==typeof s.firstChild.getAttribute&&"#"!==s.firstChild.getAttribute("href"))&&(k.attrHandle.href=function(a){return a.getAttribute("href",2)});s=null;if(document.querySelectorAll){var r=i,s=document.createElement("div");s.innerHTML="\x3cp class\x3d'TEST'\x3e\x3c/p\x3e";if(!(s.querySelectorAll&&0===s.querySelectorAll(".TEST").length)){var i=function(a,b,e,f){b=b||document;if(!f&&!i.isXML(b)){var c=/^(\w+$)|^\.([\w\-]+$)|^#([\w\-]+$)/.exec(a);if(c&&(1===b.nodeType||9===b.nodeType)){if(c[1])return u(b.getElementsByTagName(a),
e);if(c[2]&&k.find.CLASS&&b.getElementsByClassName)return u(b.getElementsByClassName(c[2]),e)}if(9===b.nodeType){if("body"===a&&b.body)return u([b.body],e);if(c&&c[3]){var j=b.getElementById(c[3]);if(j&&j.parentNode){if(j.id===c[3])return u([j],e)}else return u([],e)}try{return u(b.querySelectorAll(a),e)}catch(l){}}else if(1===b.nodeType&&"object"!==b.nodeName.toLowerCase()){var j=(c=b.getAttribute("id"))||"__sizzle__",m=b.parentNode,n=/^\s*[+~]/.test(a);c?j=j.replace(/'/g,"\\$\x26"):b.setAttribute("id",
j);n&&m&&(b=b.parentNode);try{if(!n||m)return u(b.querySelectorAll("[id\x3d'"+j+"'] "+a),e)}catch(o){}finally{c||b.removeAttribute("id")}}}return r(a,b,e,f)},p;for(p in r)i[p]=r[p];s=null}}p=document.documentElement;var z=p.matchesSelector||p.mozMatchesSelector||p.webkitMatchesSelector||p.msMatchesSelector,o=!1;try{z.call(document.documentElement,"[test!\x3d'']:sizzle")}catch(E){o=!0}z&&(i.matchesSelector=function(a,b){b=b.replace(/\=\s*([^'"\]]*)\s*\]/g,"\x3d'$1']");if(!i.isXML(a))try{if(o||!k.match.PSEUDO.test(b)&&
!/!=/.test(b))return z.call(a,b)}catch(e){}return 0<i(b,null,null,[a]).length});p=document.createElement("div");p.innerHTML="\x3cdiv class\x3d'test e'\x3e\x3c/div\x3e\x3cdiv class\x3d'test'\x3e\x3c/div\x3e";p.getElementsByClassName&&0!==p.getElementsByClassName("e").length&&(p.lastChild.className="e",1!==p.getElementsByClassName("e").length&&(k.order.splice(1,0,"CLASS"),k.find.CLASS=function(a,b,e){if("undefined"!==typeof b.getElementsByClassName&&!e)return b.getElementsByClassName(a[1])},p=null));
i.contains=document.documentElement.contains?function(a,b){return a!==b&&(a.contains?a.contains(b):!0)}:document.documentElement.compareDocumentPosition?function(a,b){return!!(a.compareDocumentPosition(b)&16)}:function(){return!1};i.isXML=function(a){return(a=(a?a.ownerDocument||a:0).documentElement)?"HTML"!==a.nodeName:!1};var D=function(a,b){for(var e,f=[],c="",j=b.nodeType?[b]:b;e=k.match.PSEUDO.exec(a);)c+=e[0],a=a.replace(k.match.PSEUDO,"");a=k.relative[a]?a+"*":a;e=0;for(var l=j.length;e<l;e++)i(a,
j[e],f);return i.filter(c,f)};window.vglnk.Sizzle=i})();