//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by ScriptStudio.rc
//
#define IDD_ABOUTBOX                    100
#define IDI_NOWAY                       113
#define IDR_MAINFRAME                   128
#define IDR_MDICHILD                    129
#define IDS_CAPTION_ERROR               130
#define IDS_CAPTION_MESSAGE             131
#define IDS_CAPTION_WARNING             132
#define IDS_CAPTION_QUESTION            133
#define IDS_ERR_EMPTYNAME               134
#define IDS_ERR_INVALIDNAME             135
#define IDS_ERR_INVALIDVALUE            136
#define IDS_ERR_VARIABLE_NOTFOUND       137
#define IDS_ERR_SYNTAX                  138
#define IDS_ERR_OPENFILE                139
#define IDS_ERR_XMLFILE                 140
#define IDS_ERR_BLOCKTYPE               141
#define IDS_ERR_CREATEFILE              142
#define IDS_FILEFILTER                  143
#define IDS_ERR_SAVEFILE                144
#define IDS_FILESAVED                   145
#define IDS_ERR_FILEERROR               146
#define IDR_BLOCKS                      201
#define IDR_NAVIGATE                    203
#define IDR_INSERT                      205
#define IDC_TREE                        208
#define IDC_SCRIPT                      209
#define IDD_RENAME                      210
#define IDD_PROP_GENERAL                211
#define IDD_PROP_EVENTS                 212
#define IDR_POPUP_TINY                  212
#define IDD_PROP_LIST                   213
#define IDR_POPUP_STANDARD              213
#define IDR_POPUP_LINKS                 214
#define IDI_HANDCLOSED                  219
#define IDI_HANDOPEN                    285
#define IDI_HANDPOINT                   286
#define IDI_PLACEITEM                   367
#define IDI_DRAGITEM                    495
#define IDC_NAME                        1000
#define IDC_NAME2                       1001
#define IDC_BLOCKEVENTS                 1001
#define IDC_SYSTEMEVENTS                1002
#define IDC_LIST                        1002
#define IDC_TITLE                       1003
#define ID_VIEW_BOOKMARKS               32772
#define ID_VIEW_EXPANDALL               32773
#define ID_VIEW_SETTINGS                32774
#define ID_SCRIPT_CHECK                 32775
#define ID_SCRIPT_BUILD                 32776
#define ID_VIEW_REPORT                  32777
#define ID_VIEW_VARIABLES               32778
#define ID_VIEW_CONSTANTS               32779
#define ID_VIEW_PROPERTIES              32780
#define ID_EDIT_DELETE                  32781
#define ID_EDIT_PROPERTIES              32782
#define ID_TOOLBAR_MAIN                 32784
#define ID_TOOLBAR_NAVIGATION           32785
#define ID_TOOLBAR_BLOCK                32786
#define ID_NAVIGATE_UP                 32794
#define ID_TOOLBAR_INSERT               32795
#define ID_EDIT_RENAME                  32850
#define ID_EDIT_LINKS_CONNECT           32851
#define ID_EDIT_LINKS_DISCONNECT        32852
#define ID_BLOCK_FIRST                  34789
#define ID_BLOCK_NOTE                   34790
#define ID_BLOCK_START                  34791
#define ID_BLOCK_STOP                   34792
#define ID_BLOCK_BOOKMARK               34793
#define ID_BLOCK_ROOT                   34794
#define ID_BLOCK_INPUT                  34796
#define ID_BLOCK_OUTPUT                 34797
#define ID_BLOCK_USERBLOCK              34799
#define ID_BLOCK_GOTO                   34800
#define ID_BLOCK_CHANGESCRIPT           34801
#define ID_BLOCK_GOSUB                  34802
#define ID_BLOCK_EVENTENABLE            34803
#define ID_BLOCK_EVENTDISABLE           34804
#define ID_BLOCK_SETVARIABLE            34805
#define ID_BLOCK_COMPARE                34806
#define ID_BLOCK_SPLITVARIABLE          34807
#define ID_BLOCK_CHOOSE                 34808
#define ID_BLOCK_DATECONVERT            34809
#define ID_BLOCK_TIMECONVERT            34810
#define ID_BLOCK_COUNTER                34811
#define ID_BLOCK_DBOPEN                 34812
#define ID_BLOCK_DBCLOSE                34813
#define ID_BLOCK_DBSELECT               34814
#define ID_BLOCK_DBSQL                  34815
#define ID_BLOCK_DBBROWSE               34816
#define ID_BLOCK_INSERT                 34817
#define ID_BLOCK_DBUPDATE               34818
#define ID_BLOCK_DBDELETE               34819
#define ID_BLOCK_DBBEGINTRANS           34820
#define ID_BLOCK_DBENDTRANS             34821
#define ID_BLOCK_DELAY                  34822
#define ID_BLOCK_FILEOPEN               34823
#define ID_BLOCK_FILEREAD               34824
#define ID_BLOCK_FILEWRITE              34825
#define ID_BLOCK_FILECLOSE              34826
#define ID_BLOCK_FILESEARCH             34827
#define ID_BLOCK_XMLLOAD                34828
#define ID_BLOCK_XMLCREATEDOCUMENT      34829
#define ID_BLOCK_XMLCLOSE               34830
#define ID_BLOCK_XMLSAVEDOCUMENT        34831
#define ID_BLOCK_DLLLOAD                34832
#define ID_BLOCK_DLLCALL                34833
#define ID_BLOCK_DLLUNLOAD              34834
#define ID_BLOCK_REGISTRY               34835
#define ID_BLOCK_FTPCONNECT             34836
#define ID_BLOCK_FTPDISCONNECT          34837
#define ID_BLOCK_FTPGETFILE             34838
#define ID_BLOCK_FTPPUTFILE             34839
#define ID_BLOCK_FTPDELETEFILE          34840
#define ID_BLOCK_FTPFINDFILE            34841
#define ID_BLOCK_HTTPGET                34842
#define ID_BLOCK_HTTPPOST               34843
#define ID_BLOCK_TCPIPCLOSE             34844
#define ID_BLOCK_TCPIPLISTEN            34845
#define ID_BLOCK_TCPIPCONNECT           34846
#define ID_BLOCK_TCPIPSEND              34847
#define ID_BLOCK_TCPRECEIVE             34848
#define ID_BLOCK_HOSTEDSCRIPT           34849
#define ID_BLOCK_LAST                   34900
#define ID_EDIT_FIND2                   57638

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        215
#define _APS_NEXT_COMMAND_VALUE         32855
#define _APS_NEXT_CONTROL_VALUE         1004
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
